### ISSUE TITLE
Detect if a USSD is currently running

### ISSUE THREAD

**Issue by trimmytech** [romellfudi/VoIpUSSD#61] opened 2020-09-29 13:20 UTC
I have an app that runs multiple USSD in intervals , how do i check if a USSD is currently running so they wont overlapp each other ??

**Comment by romellfudi** [comment] 2020-09-29 14:11
It's not a bug.
You should handle it . 
Well , As I know it works like any call, the operative system dials up one at time

**Comment by trimmytech** [comment] 2020-09-29 14:15
sorry about the label.
i now OS handles one at a time .
 is there any way to check in code ??? so the app doesnt even try to dial it while one is runnig ?

i will appreciate a sample code please.

**Comment by romellfudi** [comment] 2020-09-29 15:12
Actually, there is a protected variable in Controller [class](https://github.com/romellfudi/VoIpUSSD/blob/c739ccb6d8729061bfe1f9cb1ecc535d171dfd11/ussd-library/src/main/java/com/romellfudi/ussdlibrary/USSDController.java#L51). You could return a flag as to know whether or no it is being run

**Comment by Nivekiba** [comment] 2022-11-25 15:40
Hello @romellfudi i permit my self to reopen this issue.
While the variable in Controller class in "protected", there is no way to know if it's running or not.

**Comment by ebran-flow** [comment] 2023-05-12 05:12
@romellfudi, I'm trying to do the same thing. Is it possible now?

**Comment by romellfudi** [comment] 2023-05-13 14:58
@ebran-flow  just try debugging

**Comment by coder-eb** [comment] 2023-05-13 15:00
Do you mean I should expose the variable using a method or something?

**Comment by ibstelix** [comment] 2023-07-08 12:49
hi coder-eb, you can manage yourself the state:
1. you set a flag "running" to true
2. you send the ussd call
3. if failed or if you get ussd response : you set the flag "running" to false
4. before running a new ussd request, you check if the "running" flag is true or false

**Comment by romellfudi** [comment] 2023-07-28 02:38
@coder-eb @ibstelix Exactly, actually I didn't expose before but you just can encapsulate it as to check running process,

Please let me know if I can close the issue

**Comment by coder-eb** [comment] 2023-09-24 13:08
Hi @ibstelix, Thanks for the suggestion. 

@romellfudi Kindly close the issue

**Comment by romellfudi** [comment] 2023-10-01 14:14
Hi @coder-eb absolutely. Please consider donating PayPal to keep active the community

**Closed** 2023-10-01 14:14 UTC
Labels: invalid
